[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /tmp/klippy_uds

[file_manager]

[authorization]
force_logins: False
trusted_clients:
    0.0.0.0/0
cors_domains:
    *
[history]

[octoprint_compat]

[machine]
provider: supervisord_cli
validate_service: False
validate_config: False
