[supervisord]
nodaemon=true
logfile=/home/developer/printer_data/logs/supervisord.log
pidfile=/tmp/supervisord.pid
childlogdir=/home/developer/printer_data/logs

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0770                      ; Allows the owner and group to read/write
chown=root:developer            ; Gives group ownership to your developer

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[program:simulavr]
command=/bin/bash -lc 'sleep 2; exec /home/developer/klipper/scripts/avrsim.py -m atmega644p -s 20000000 -b 250000 /home/developer/klipper/out/klipper.elf'
environment=PYTHONPATH="/home/developer/simulavr/build/pysimulavr/"
user=developer
autostart=true
autorestart=true
priority=10
stopasgroup=true
killasgroup=true
stdout_logfile=/home/developer/printer_data/logs/simulavr.stdout.log
stderr_logfile=/home/developer/printer_data/logs/simulavr.stderr.log

[program:klipper]
command=/home/developer/klippy-env/bin/python /home/developer/klipper/klippy/klippy.py /home/developer/printer_data/config/printer.cfg -a /tmp/klippy_uds -l /home/developer/printer_data/logs/klippy.log
user=developer
autostart=true
autorestart=true
priority=20
startsecs=2
stopasgroup=true
killasgroup=true
stdout_logfile=/home/developer/printer_data/logs/klippy.stdout.log
stderr_logfile=/home/developer/printer_data/logs/klippy.stderr.log

[program:moonraker]
command=/home/developer/moonraker-env/bin/python /home/developer/moonraker/moonraker/moonraker.py -c /home/developer/printer_data/config/moonraker.conf -l /home/developer/printer_data/logs/moonraker.log
user=developer
autostart=true
autorestart=true
priority=30
startsecs=2
stdout_logfile=/home/developer/printer_data/logs/moonraker.stdout.log
stderr_logfile=/home/developer/printer_data/logs/moonraker.stderr.log

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
priority=40
stdout_logfile=/home/developer/printer_data/logs/nginx.stdout.log
stderr_logfile=/home/developer/printer_data/logs/nginx.stderr.log
